name: pynvel
channels: !!python/tuple
- defaults
dependencies:
- alabaster=0.7.7=py34_0
- babel=2.2.0=py34_0
- colorama=0.3.6=py34_0
- cython=0.23.4=py34_0
- docutils=0.12=py34_1
- jinja2=2.8=py34_0
- markupsafe=0.23=py34_0
- mkl=11.3.1=0
- msvc_runtime=1.0.1=vc10_0
- numpy=1.10.4=py34_0
- pandas=0.18.0=np110py34_0
- pip=9.0.1=py34_0
- pygments=2.1.1=py34_0
- python=3.4.4=2
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- setuptools=20.2.2=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.1=py34_0
- sphinx=1.3.5=py34_0
- sphinx_rtd_theme=0.1.9=py34_0
- wheel=0.29.0=py34_0
- pip:
  - nose2==0.6.5
  - pockets==0.3
  - sphinx-bootstrap-theme==0.4.8
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-napoleon==0.5.0
